# Generated by Django 4.2.19 on 2025-03-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myhello", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="location",
            new_name="CourseTitle",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="title",
            new_name="Department",
        ),
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="photo",
        ),
        migrations.AddField(
            model_name="post",
            name="Instructor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
